### ISSUE TITLE
Add support for broadcom cpus

### ISSUE THREAD

**Issue by Mat-Alm** [SySS-Research/nand-dump-tools#1]
Hi! I want to know if it's possible to add broadcom cpus to the supported list. 
I have a module that have a cygnus series cpu (cortex A9) BCM9583xx and it have a nand flash with this configuration: 

NAND device: Manufacturer ID: 0x98, Chip ID: 0xdc (Toshiba NAND 512MiB 3,3V 8-bit), 512MiB, page size: 2048, OOB size: 64
iproc_nand: timing mode 4
proc_nand: following bootloader settings
NAND 8-bit 5-addr-cycles
512MiB total, 128KiB blocks, 2KiB pages
8bit/512B BCH-ECC 16B/512B OOB
iproc_nand: ECC correction status threshold set to 5 bit
proc_nand: user oob per page: 6 bytes (4 steps)

I also found some code in C at this repositories:

https://github.com/StrayLightning/brcm-nand-bch

https://github.com/ak-hard/brcm-nand-bch

 But your code is in python and i don't know if the libraries are compatible with the ones above.

If you can help I will be thankful! I also can attach some of my nand dump if it helps!

**Comment by dylangerdaly** [comment]
I have a dump that uses a broadcom NAND driver, any idea how to remove the OOB/ECC? I have BCH-8.
